apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookworm-deployment
  namespace: bookworm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookworm
  template:
    metadata:
      labels:
        app: bookworm
    spec:
      containers:
      - name: bookworm-container
        image: crbookworm.azurecr.io/imagebookworm:${{ github.sha }}
        ports:
        - containerPort: 8080
        env:
        - name: ACCOUNT_HOST
          valueFrom:
            secretKeyRef:
              name: cosmosdb-secret
              key: ACCOUNT_HOST
        - name: ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: cosmosdb-secret
              key: ACCOUNT_KEY
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: cosmosdb-secret
              key: DB_NAME
        - name: DB_THROUGHPUT
          value: "400"