apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookworm-deployment
  namespace: bookworm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookworm
  template:
    metadata:
      labels:
        app: bookworm
    spec:
      containers:
      - name: bookworm-container
        image: crbookworm.azurecr.io/imagebookworm:${{ github.sha }}
        ports:
        - containerPort: 8080
        env:
        - name: ACCOUNT_HOST
          value: ${{ secrets.COSMOSDB_HOST }}
        - name: ACCOUNT_KEY
          value: ${{ secrets.COSMOSDB_KEY }}
        - name: DB_NAME
          value: ${{ secrets.COSMOSDB_DBNAME }}
        - name: DB_THROUGHPUT
          value: ${{ secrets.COSMOSDB_THROUGHPUT }}