apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: bookworm
spec:
  template:
    metadata:
      lables:
        job-name: test-job
    spec:
      containers:
      - name: test-container
        image: crbookworm.azurecr.io/imagebookwormtest:${{ github.sha }}
      restartPolicy: Never
  backoffLimit: 4