apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: bookworm
spec:
  template:
    metadata:
      labels:
        job: test-job
    spec:
      containers:
      - name: test-job
        image: crbookworm.azurecr.io/imagebookwormtest:${{ github.sha }}
        command: ["mvn", "clean", "test"]
      restartPolicy: Never
  backoffLimit: 4