apiVersion: v1
kind: Service
metadata:
  name: bookworm-service
  namespace: bookworm
spec:
  type: LoadBalancer
  selector:
    app: bookworm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080